---
- name: Generating In-Memory Inventory
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers

    - name: Add Host
      add_host:
        name: "{{ item.public_v4 }}"
        ansible_user: cloud-user
        ansible_ssh_private_key_file: "~/.ssh/openstack.pem"
        group: "{{ item.metadata.group }}"
      loop: "{{ r_os_servers.openstack_servers }}"
